### PR TITLE
error handling and web server logging fixes

### LINKED ISSUE #1958: handle_internalunixusertokenread throwing 500's without context
### I did this

Hit the `handle_internalunixusertokenread` endpoint with... something.

### I expected the following

* not a 500 error
* logs showing what API endpoint was hit

### Kanidm version (and git commit)

Container version: kanidmd 1.1.0-rc.14-dev (... the git commit isn't showing 😡 )

ghcr.io/kanidm/kanidmd@sha256:4e2265a2e73f131d0fdda70dc4709b966359907c8736aa6520f7ae796904e269

### Operating System / Version

OpenSUSE Tumbleweed something something.

### Any other comments

Logs:

```
request [ 271µs | 21.40% / 100.00% ]
┝━ handle_internalunixusertokenread [ 213µs | 16.55% / 78.60% ]
│  ┝━ validate_and_parse_token_to_ident [ 168µs | 62.05% ]
│  ┕━ ｉ [info]: Error resolving  as gidnumber continuing ... | event_tag_id: 3 | err: InvalidValueState
┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 0 ms
```

### PR DESCRIPTION
**Pull request by yaleman**
* Fixes #1958
* adds some tests relating to #1958
* Cleans up some URL-generation in the client code
* chases some clippy lints
* fixes the setup_dev_environment script to support the new UNIX socket system

Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: libs/client/src/lib.rs [hunk 1]
```diff
@@ -447,8 +447,14 @@ impl KanidmClient {
         &self.origin
     }
 
+    /// Returns the base URL of the server
     pub fn get_url(&self) -> &str {
-        self.addr.as_str()
+        &self.addr
```
Comment (Firstyear) [inline libs/client/src/lib.rs:452]: I wonder if it's worth making this a URL type since then we can do .join for safe append of endpoints.

Comment (Firstyear) [reply libs/client/src/lib.rs:452]: Guess it depends if reqwest takes a url or str? If url supports .as_str() then it's probably worth.

File: server/core/src/actors/v1_read.rs [hunk 2]
```diff
@@ -618,10 +618,15 @@ impl QueryServerReadV1 {
             .qs_read
             .name_to_uuid(uuid_or_name.as_str())
             .map_err(|e| {
+                // sometimes it comes back as empty which is bad
+                let uuid_or_name_val = match uuid_or_name.is_empty() {
+                    true => "<empty uuid_or_name>",
```
Comment (Firstyear) [inline server/core/src/actors/v1_read.rs:623]: comment here that `<empty` is safe here since a valid username or uuid can never start with a `<`.

File: server/testkit/src/lib.rs [hunk 3]
```diff
@@ -102,25 +102,24 @@ pub async fn create_user(rsclient: &KanidmClient, id: &str, group_name: &str) {
         .expect("Failed to create the user");
 
     // Create group and add to user to test read attr: member_of
-    #[allow(clippy::expect_used)]
+    #[allow(clippy::panic)]
```
Comment (Firstyear) [inline server/testkit/src/lib.rs:105]: Why panic over expect?

**Review by Firstyear — APPROVED** [review]

File: server/core/src/actors/v1_read.rs (hunk 2 above)
Comment (yaleman) [reply server/core/src/actors/v1_read.rs:623]: Noted, updated. We're only logging it but it's good to have it. :smile:

File: server/testkit/src/lib.rs (hunk 3 above)
Comment (yaleman) [reply server/testkit/src/lib.rs:105]: I tried an `expect(format!(...))``, but clippy yelled at me and told me to go this way because of the [expect_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#/expect_fun_call) lint.
