### PR TITLE
client_secret_post auth for oauth2 endpoints

### LINKED ISSUE #3827: client_secret_post authentication does not work for token_endpoint, introspection_endpoint and revocation_endpoint
### I did this

Both `https://idm.example.com/oauth2/openid/:client_id:/.well-known/oauth-authorization-server` and `https://idm.example.com/oauth2/openid/:client_id:/.well-known/openid-configuration` report that `client_secret_post` is supported for the token, introspection and revocation endpoints but none support the method.

### I expected the following

The endpoints respond with the correct response.

### This happened instead

The endpoints will respond with 401 due to not being able to authenticate.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.7.3`
- Are you running it in a container? If so, which image/tag?: `latest`
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux fabian-ml-amd64-framework 6.12.10-76061203-generic #202412060638~1753385880~24.04~670f438 SMP PREEMPT_DYNAMIC Thu J x86_64 x86_64 x86_64 GNU/Linux`

### Any other comments

After a short discussion with @yaleman it seems that `client_secret_post` authentication is supposed to work but doesn't.

Example logs:
```
11accd7b-614a-4807-ba36-5aaee54caeeb INFO     ┕━ ｉ [info]:  | connection_addr: [::ffff:127.0.0.1]:33034 | client_ip_addr: ::ffff:127.0.0.1
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 INFO     request [ 206µs | 87.63% / 100.00% ] method: POST | uri: /oauth2/token/introspect | version: HTTP/1.1
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 INFO     ┝━ ｉ [info]:  | connection_addr: [::ffff:172.18.0.2]:51708 | client_ip_addr: ::ffff:172.18.0.2
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 INFO     ┝━ pre_validate_client_auth_info [ 6.47µs | 2.79% / 3.15% ]
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 INFO     │  ┕━ validate_client_auth_info_to_uat [ 732ns | 0.36% ]
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 INFO     ┝━ handle_oauth2_token_introspect [ 19.0µs | 9.22% ]
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 WARN     │  ┕━ 🚧 [warn]: OAuth2 client_id not provided by basic authz | event_tag_id: 2
b9b229e8-dc14-47c1-86c6-2c7af1bcd452 WARN     ┕━ 🚧 [warn]:  | latency: 229.782µs | status_code: 401 | kopid: "b9b229e8-dc14-47c1-86c6-2c7af1bcd452" | msg: "client error"
```

### PR DESCRIPTION
**Pull request by yaleman**
# Change summary

- client_secret_post auth for oauth2 endpoints
- updates the tests to use both basic and post auth

Fixes #3827 

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by yaleman** [comment]
@Firstyear plz stamp 💟

File: server/lib/src/idm/oauth2.rs [hunk 1]
```diff
@@ -2353,7 +2343,7 @@ impl IdmServerProxyReadTransaction<'_> {
         // check the secret.
         match &o2rs.type_ {
             OauthRSType::Basic { authz_secret, .. } => {
-                if authz_secret != &secret {
+                if Some(authz_secret.to_owned()) != secret {
```
Comment (Firstyear) [inline server/lib/src/idm/oauth2.rs]: I think here you can do Some(authz_secret) != secret.as_ref() so that they both become Option<&...> rather than doing a .to_owned to clone.

File: server/lib/src/idm/oauth2.rs [hunk 2]
```diff
@@ -2885,7 +2875,7 @@ impl IdmServerProxyReadTransaction<'_> {
     }
 }
 
-fn parse_basic_authz(client_authz: &str) -> Result<(String, String), Oauth2Error> {
+fn parse_basic_authz(client_authz: &str) -> Result<(String, Option<String>), Oauth2Error> {
```
Comment (Firstyear) [inline server/lib/src/idm/oauth2.rs]: I think maybe we should make this `(String, Option<String>) ` a type like Oauth2ClientAuthInfo or similar just to tidy it and allow future other auth types.

File: server/lib/src/idm/oauth2.rs [hunk 3]
```diff
@@ -531,6 +531,21 @@ impl Oauth2ResourceServers {
     }
 }
 
+/// For when you've got the bearer auth and the post auth and you just want the resulting auth attempt
+fn get_client_auth(
```
Comment (Firstyear) [inline server/lib/src/idm/oauth2.rs:536]: Re the Oauth2ClientAuthInfo struct suggestion, it's so that here we can eventually do something like mTLS auth because we have that info in ClientAuthInfo. So I think this is a good extractor for building the struct.

File: server/lib/src/idm/oauth2.rs (hunk 2 above)
Comment (yaleman) [reply server/lib/src/idm/oauth2.rs]: Yep, have made a `ClientAuth` in proto
