### PR TITLE
Resolve issues with dyngroup members

### LINKED ISSUE #1942: Failed to start server core
### I did this

I start kanidm as I always do locally
```bash
docker run --rm -it \
    -p 127.0.0.1:8443:8443 \
    -v ./data:/data \
    -u 1000:1000 \
    --name kanidm \
    kanidm/serve
```

### I expected the following

I expected the server to start, as it did the days/weeks before.

### What actually happened
```
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 INFO     ┝━ ｉ [info]: Removing expired auth session | session_id: fe9cec12-017c-4804-9fe6-7d5fc024730a
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┝━ 🚨 [error]: UUID reference set size differs from query result size <fast path, no uuid info available> | event_tag_id: 1
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┝━ 🚨 [error]: Post-Modify operation failed (plugin), Plugin(ReferentialIntegrity("Uuid referenced not found in database")) | event_tag_id: 1
1f6ae7b4-47c3-4aa4-b2e2-bdf7c106d139 ERROR    ┕━ 🚨 [error]: initialise_idm p3 -> result | event_tag_id: 1 | res: Err(Plugin(ReferentialIntegrity("Uuid referenced not found in database")))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Unable to setup query server or idm server -> Plugin(ReferentialIntegrity("Uuid referenced not found in database"))
00000000-0000-0000-0000-000000000000 ERROR    🚨 [error]: Failed to start server core!
```
### Kanidm version (and git commit)

kanidmd 1.1.0-beta.13

The data folder was created with the previous version.

### Operating System / Version

official container running on manjaro workstation

`Linux milkshake 6.1.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 x86_64 GNU/Linux`

### Any other comments

I just shutdown the system in the evening, start it in the morning and get back to work. It's my local development system and I talk to it via API and CLI.

I probably wouldn't have reported it and would just blame myself for unclean shutdown or something. However, @Kranzes in Matrix ran into the same issue when upgrading from previous to latest version on his Nix system. He downgraded, I nuked my data folder and started over. But something seems broken.

Full log can be found [here](https://gist.githubusercontent.com/tumbl3w33d/94db18d62cb20cf544b0311881f0657a/raw/b993a848bb62bca8ccd516241780551807f02acc/gistfile1.txt).

P.S.: I used kani's tools to do an integrity check and executed the vacuum operation. No problems detected, issue not fixed.

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #1942 - I'm not 100% sure of the origin, and I need to dig through the git repos, but we appeard to have duplicated dynmember into member at some point. This caused a failure to start, as dyngroups have a special exemption in refint to avoid checking, but member *does not*. As a result, this caused the server to fail to start.

This adds a "one shot" cleanup of member from dyngroups, adds the needed acp's to allow viewing of dynmembers, a verification to tests that members aren't being added, and a dbscan quarantine command to assist with future debugging and entry isolation when required.

Checklist

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/lib/src/plugins/refint.rs [hunk 1]
```diff
@@ -164,7 +164,7 @@ impl Plugin for ReferentialIntegrity {
         qs.internal_apply_writable(work_set)
     }
 
-    #[instrument(level = "debug", name = "verify", skip(qs))]
+    #[instrument(level = "debug", name = "verify::refint", skip_all)]
```
Comment (yaleman) [inline server/lib/src/plugins/refint.rs:167]: shouldn't this be refint::verify ?

**Review by yaleman — CHANGES_REQUESTED** [review]
nit picked 😄

File: server/lib/src/plugins/refint.rs (hunk 1 above)
Comment (Firstyear) [reply server/lib/src/plugins/refint.rs]: fixed!

**Review by yaleman — APPROVED** [review]
