### PR TITLE
20251005 multiple accept

### LINKED ISSUE #3923: Support binding on multiple addresses
### I did this

Searched documentation, looked at the code, observed that it's not currently an option. Also tried just specifying the port (`:8443`) which doesn't work.

### I expected the following

kanidmd should be configurable to bind to both IPv4 and IPv6 sockets.

### This happened instead

It can't.

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.7.4
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: FreeBSD pkg
- Operating System / Version (On Unix please post the output of `uname -a`):
`FreeBSD kanidm 14.3-RELEASE FreeBSD 14.3-RELEASE-p5 GENERIC amd64`

### PR DESCRIPTION
**Pull request by Firstyear**
# Change summary

- Supporting binding to multiple addresses. This is useful on FreeBSD which has a separate ipv4/ipv6 stack, where linux has a ipv4 in 6 mapping feature. 

Fixes #3923

Checklist

- [x] This PR contains no AI generated code
- [x] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/daemon/src/main.rs [hunk 1]
```diff
@@ -988,7 +988,7 @@ async fn kanidm_main(config: Configuration, opt: KanidmdParser) -> ExitCode {
                     // the replace covers when you specify an ipv6-capable "all" address
                     format!(
                         "https://{}/status",
-                        config.address.replace("[::]", "localhost")
+                        config.address[0].replace("[::]", "localhost")
```
Comment (yaleman) [inline server/daemon/src/main.rs:991]: This'll likely catch folks but otherwise ... it looks ok 😄

Comment (Firstyear) [reply server/daemon/src/main.rs:991]: Yeah I wasn't sure what else to do - we enforce that there is at least on address so that's fine. But we have to make some assumption about the health check and in this case that it's the first address we attempt it on.
