### PR TITLE
Unix gid duplicate fix

### LINKED ISSUE #1875: When changing a unix group gid the old gid isn't removed, resulting in the group having 2 gids
### On a newly create dev server run the following: 
- kanidm group create demo_group --name idm_admin
- kanidm group posix set --name idm_admin demo_group
- kanidm group posix set --name idm_admin demo_group --gidnumber 2001

### I expected the following

Success adding POSIX configuration for group demo_group

### Kanidm version (and git commit)

version 1.1.0-beta.13-dev (1.1.0-beta.13-dev)

[kanidm(d) --version]
kanidmd version: kanidmd 1.1.0-beta.13-dev

### Operating System / Version

5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by Seba-T**
Fixes #1875

Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/core/src/actors/v1_write.rs [hunk 1]
```diff
@@ -1108,6 +1108,7 @@ impl QueryServerWriteV1 {
             "class".into(),
             Value::new_class("posixgroup"),
         )))
+        .chain(iter::once(Some(Modify::Purged("gidnumber".into()))))
```
Comment (Firstyear) [inline server/core/src/actors/v1_write.rs:1111]: What happens if the user changes another attribute but not the gid here now? I think this purge needs to be associated only if a gid is actually set too.

File: server/testkit/tests/proto_v1_test.rs [hunk 2]
```diff
@@ -532,6 +532,12 @@ async fn test_server_rest_posix_lifecycle(rsclient: KanidmClient) {
         .idm_group_unix_extend("posix_group", None)
         .await
         .unwrap();
+    // here we check that we can successfully change the gid without breaking anything
```
Comment (Firstyear) [inline server/testkit/tests/proto_v1_test.rs:535]: Change another attribute and check the gid stays the same ;)

**Review by Firstyear — CHANGES_REQUESTED** [review]

File: server/core/src/actors/v1_write.rs (hunk 1 above)
Comment (Seba-T) [reply server/core/src/actors/v1_write.rs:1111]: I think I should move it inside the map then

Comment (Firstyear) [reply server/core/src/actors/v1_write.rs:1111]: Or just restructure the code to make it clearer what the intent is.

File: server/testkit/tests/proto_v1_test.rs (hunk 2 above)
Comment (Seba-T) [reply server/testkit/tests/proto_v1_test.rs:535]: what other attributes can I change besides the gid? Because in `GroupUnixExtend` I just see `pub gidnumber: Option<u32>,`

Comment (Firstyear) [reply server/testkit/tests/proto_v1_test.rs:535]: 🤔 good point. But if the person runs the command with a "None" in the gid it should be idempotent and not change the gid.

Comment (Seba-T) [reply server/testkit/tests/proto_v1_test.rs:535]: agreed, so I'll ensure that won't happen

**Review by Firstyear — APPROVED** [review]
