### PR TITLE
Authentication shortcut to get a RW session

### LINKED ISSUE #1940: Shortcut for authenticating with the API?
I am using the kanidm API to programatically modify the assets in there. With the latest release, the initial authentication got more complicated. Before, I just created a session by POSTing to /v1/auth (init: username). Then a second POST initiated the authentication (begin: password) and a third POST (cred: password) actually logged me in and I could start operating.

In the newest version this leaves me with a read-only session. I found out that I need to use the /v1/reauth endpoint to escalate privileges, but this means I need 2 more requests. First I POST (token: null, which I found weird). That gives me a new session ID, so the one I received a second ago is already obsolete and I continue with this one. Now I POST once more to /v1/auth (cred: password) using the new session as header.

It's the same behavior with the kanidm CLI. You login and if you want to make a write operation right after, you need to reauth, so you repeat your auth steps you did 5 seconds ago.

I understand the idea behind it and you are the experts on authentication. My question is: Is there no safe shortcut, like when initiating a session to tell the server "I'd like to start with a write session"?

Oh, and by the way: If I programmatically fire these 5 requests to initially auth, I always run into a timing error: `Ident session is not present in entry. Perhaps replication is delayed?`

I worked around that with a "sleep" statement in my script before talking to the reauth endpoint, but well…

### PR DESCRIPTION
**Pull request by scabrero**
What do you think about this approach? I am not convinced about the `privileged` name.

Do we also want to expose this functionality in the client library? E.g.:
`$ kanidm login --privileged`

Fixes #1940 

Checklist

- [X] This pr contains no AI generated code
- [X] cargo fmt has been run
- [X] cargo clippy has been run
- [X] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: proto/src/v1.rs [hunk 1]
```diff
@@ -917,6 +917,8 @@ pub enum AuthStep {
     Init2 {
         username: String,
         issue: AuthIssueSession,
+        #[serde(skip_serializing_if = "Option::is_none")]
+        privileged: Option<bool>,
```
Comment (Firstyear) [inline proto/src/v1.rs:921]: I think you can make this just `bool` because bool impls default, and bool defaults to false. That way you can have `#[serde(default)]` here instead. That then makes some of your later code a bit easier.

File: server/lib/src/idm/authsession.rs [hunk 2]
```diff
@@ -1327,72 +1341,98 @@ mod tests {
...
-        let cred = Credential::new_password_only(&p, "test_password").unwrap();
-        account.primary = Some(cred);
-
-        let (async_tx, mut async_rx) = unbounded();
-        let (audit_tx, mut audit_rx) = unbounded();
-
-        // now check
-        let (mut session, pw_badlist_cache) =
-            start_password_session!(&mut audit, account, &webauthn);
+    macro_rules! start_session_simple_password_mech {
```
Comment (Firstyear) [inline server/lib/src/idm/authsession.rs:1344]: Why make this a macro? Why not leave it as a function?

File: server/lib/src/idm/authsession.rs [hunk 3]
```diff
@@ -1327,72 +1341,98 @@ mod tests {
...
+            assert!(audit_rx.blocking_recv().is_none());
+        }};
+    }
 
-        drop(async_tx);
-        assert!(async_rx.blocking_recv().is_none());
-        drop(audit_tx);
-        assert!(audit_rx.blocking_recv().is_none());
+    #[test]
+    fn test_idm_authsession_simple_password_mech() {
```
Comment (Firstyear) [inline server/lib/src/idm/authsession.rs:1433]: Should be two seperate tests rather than the sequential calls here like this.

File: server/testkit/tests/proto_v1_test.rs [hunk 4]
```diff
@@ -1460,3 +1462,178 @@ async fn test_server_user_auth_reauthentication(rsclient: KanidmClient) {
     eprintln!("{:?} {:?}", now, uat.purpose);
     assert!(uat.purpose_readwrite_active(now));
 }
+
+macro_rules! start_password_session {
```
Comment (Firstyear) [inline server/testkit/tests/proto_v1_test.rs:1466]: Generally we should avoid macros unless really needed for small ergonomic tasks. Better to use functions.

**Review by Firstyear — CHANGES_REQUESTED** [review]

**Comment by Firstyear** [comment]
> Do we also want to expose this functionality in the client library? E.g.:
> `$ kanidm login --privileged`

To start with, no, I think we should leave this as api only. The cli is a bit more targetted to human users and already has some elements to assist with this. 


Generally though, looks really good for the first PR. I think that macros should be avoided a bit more here as they add a chunk to compile times and generally make it a bit harder to trace some things. We used a lot of macros in the past and have been trying to "undo it" for functions. Generally macros are good for small ergonomic wrappers (like vec![] or btreemap![]) or allowing some variable arg situations in some cases.

File: proto/src/v1.rs (hunk 1 above)
Comment (scabrero) [reply proto/src/v1.rs]: Done.

**Review by Firstyear — APPROVED** [review]
This looks really good!
