### PR TITLE
OAuth2 scopes validation logging missing details

### LINKED ISSUE #2316: OAuth2 scopes validation logging missing details
Currently the error shows "Invalid oauth2 request - requested scopes failed to pass validation rules | event_tag_id: 1"

Need to add which scopes were requested so we can work out why it was wrong 😄

### PR DESCRIPTION
**Pull request by yaleman**
Fixes #2316

Checklist

- [x] This pr contains no AI generated code
- [x] cargo fmt has been run
- [x] cargo clippy has been run
- [x] cargo test has been run and passes

### CODE REVIEW

File: server/lib/src/idm/oauth2.rs [hunk 1]
```diff
@@ -502,15 +502,15 @@ impl<'a> IdmServerProxyWriteTransaction<'a> {
...
+            admin_warn!("Invalid OAuth2 client_id");
             Oauth2Error::AuthenticationRequired
         })?;
 
         // check the secret.
         match &o2rs.type_ {
             OauthRSType::Basic { authz_secret, .. } => {
                 if authz_secret != &secret {
-                    security_info!("Invalid oauth2 client_id secret");
+                    security_info!("Invalid OAuth2 client_id secret");
```
Comment (Firstyear) [inline server/lib/src/idm/oauth2.rs:513]: While we're looking, let's add "This can happen if you were expecting a public client" or similar, see chat today.

File: server/lib/src/idm/oauth2.rs [hunk 2]
```diff
@@ -1342,14 +1342,20 @@ impl<'a> IdmServerProxyReadTransaction<'a> {
...
+            admin_error!("Invalid OAuth2 request - must contain at least one requested scope");
             return Err(Oauth2Error::InvalidRequest);
         }
 
         // Check the scopes by our scope regex validation rules.
         if !req_scopes.iter().all(|s| OAUTHSCOPE_RE.is_match(s)) {
             admin_error!(
-                "Invalid oauth2 request - requested scopes failed to pass validation rules"
+                "Invalid OAuth2 request - requested scopes ({}) failed to pass validation rules - all need to match the regex {}",
+                req_scopes
```
Comment (Firstyear) [inline server/lib/src/idm/oauth2.rs:1353]: Might be clearer to put this over two lines with "let failed_scopes = ..." then print that.

**Review by Firstyear — APPROVED** [review]
Minor changes, but looks good :)

**Review by Firstyear — APPROVED** [review]
