### PR TITLE
20250213 patch used wrong acp

### LINKED ISSUE #3270: idm_admin cannot modify entry-mananged-by attribute
### I did this

- Set up a new Kanidm instance.
- Create a new Group with an `entry-managed-by` person with `idm_admin`.
- Try to update `entry -managed-by` for that group with `idm_admin`.

### I expected the following

It updates it correctly to the new `entry-managed-by`.

### This happened instead

```
INFO     request [ 245µs | 13.50% / 100.00% ] method: PUT | uri: /v1/group/managed/_attr/entry_managed_by | version: HTTP/1.1
INFO     ┝━ set_attribute [ 212µs | 52.51% / 86.50% ]
INFO     │  ┝━ validate_client_auth_info_to_ident [ 83.3µs | 33.99% ]
INFO     │  │  ┕━ ｉ [info]: A valid limited session value exists for this token | event_tag_id: 10
INFO     │  ┝━ ｉ [info]: modify initiator | event_tag_id: 10 | name: User( idm_admin@idm.localhost, 00000000-0000-0000-0000-000000000018 ) (c2efdc60-6426-4365-8b79-85cdf73baac0, read write)
INFO     │  ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( idm_admin@idm.localhost, 00000000-0000-0000-0000-000000000018 ) (c2efdc60-6426-4365-8b79-85cdf73baac0, read write)
ERROR    │  ┝━ 🚨 [error]: requested_pres is not a subset of allowed | event_tag_id: 12
ERROR    │  ┝━ 🚨 [error]: requested_pres: {EntryManagedBy} !⊆ allowed: {AuthSessionExpiry, AuthPasswordMinimumLength, Class, CredentialTypeMinimum, Description, GidNumber, LimitSearchMaxResults, LimitSearchMaxFilterTest, Mail, Member, Name, PrivilegeExpiry, WebauthnAttestationCaList, AllowPrimaryCredFallback} | event_tag_id: 12
INFO     │  ┕━ ｉ [info]: denied ❌ - modify may not proceed | event_tag_id: 11
WARN     ┕━ 🚧 [warn]:  | latency: 244.982µs | status_code: 403 | kopid: "a6bc0016-7140-4dd8-9efa-09f1e7c5595f" | msg: "client error"
```

### Kanidm version details

- Output of `kanidm(d) version: `kanidmd 1.4.4`
- Are you running it in a container? If so, which image/tag?: `kanidm/server:latest`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments

I expect that admins can always revert permissions but I don't know if there are any concerns to avoid it. Furthermore, I don't see any easy way of removing an `entry-managed-by` attribute more than recreating the group.

### PR DESCRIPTION
**Pull request by Firstyear**
Major refactor of migrations to improve durability.

    Migrations and server bootstrap are very interconnected processes
    and in this we'll be addressing and improving both.

    Server bootstrap was performed by creating base entries in phases,
    eventually bringing up enough of the *oldest* supported server
    minimum remigration level, to then allow triggering of migrations.

    Migrations then applied "patches" effectively ontop of this minimum
    level to update entries to what they should be in newer versions of
    the server.

    This scheme has it's pros and cons, but the major con was that to
    remove a migration meant squashing it's content back into the
    minimum remigration level, and this was a human process that was
    quite error prone and difficult to automate. As well, this scheme
    also led to cases where the patch migrations would sometimes *not*
    reflect all the needed changes or content, or in one case was actually
    undone by a patchlevel fix up that was required to address a bug.

    Invariably this led to issues, and cases where a new server may have
    different content to a migrated one - not exactly what we want!

    This is a new migration scheme that addresses this fragility. However
    what it trades is verbosity of the content.

    Rather than having a base set of entries and patching/updating small
    sections ontop, we have migration data folders that contain the full
    set of entries as they should appear at that migration level. This
    makes the bootstrap process easier as we can just apply the migration
    level as a whole, and targetted to what precise version we want.

    This also makes migrations more durable as the content is explicitly
    copied and all entries fully applied, so there is no risk that a
    migration or data change can be forgotten or applied incorrectly. We
    are expressing the full state of what our builtin and provided entries
    should be.

    Finally this rips out a number of places where migration data was being
    used as test case data. Not all of these have been replaced (notably
    in authsession with Account), but the majority have and have been replaced
    with clearer use of constants rather than building whole entries just to
    access the name and throw them away for example.

Fixes #3270

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
Two bonus commits that make test execution ~10% faster, and significantly faster to compile.

File: server/lib/src/migration_data/dl8/access.rs [hunk 1]
```diff
@@ -0,0 +1,2637 @@
...
+    /// is sufficient for you to receive the access control.
+    Group(Vec<Uuid>),
+    EntryManager,
+}
+
+#[derive(Clone, Debug, Default)]
+/// Objects that are affected by the rules of this ACP.
+pub enum BuiltinAcpTarget {
+    #[default]
+    None,
```
Comment (CEbbinghaus) [inline server/lib/src/migration_data/dl8/access.rs:56]: Just wondering. Wouldn't we want a invalid target to be unrepresentative? Why define None

File: server/lib/src/migration_data/dl8/schema.rs [hunk 2]
```diff
@@ -0,0 +1,1506 @@
...
+    name: Attribute::DisplayName,
+    description: "The publicly visible display name of this person".to_string(),
+
+    index: vec![IndexType::Equality],
+    sync_allowed: true,
+    syntax: SyntaxType::Utf8String,
+    ..Default::default()
+};
+
+pub static ref SCHEMA_ATTR_DISPLAYNAME_DL7: SchemaAttribute = SchemaAttribute {
```
Comment (CEbbinghaus) [inline server/lib/src/migration_data/dl8/schema.rs:21]: `DL8` if anything. But now that they have been moved into seperate modules we shouldn't need the naming right? would be `dl8::SCHEMA_ATTR_DISPLAYNAME`

This also goes for the other Domain Levels

File: server/lib/src/migration_data/dl8/system_config.rs [hunk 3]
```diff
@@ -0,0 +1,1073 @@
...
+            Attribute::BadlistPassword,
+            Value::new_iutf8("100preteamare")
+        ),
+        (Attribute::BadlistPassword, Value::new_iutf8("14defebrero")),
+        (Attribute::BadlistPassword, Value::new_iutf8("1life1love")),
+        (Attribute::BadlistPassword, Value::new_iutf8("1life2live")),
+        (Attribute::BadlistPassword, Value::new_iutf8("1love1life")),
+        (Attribute::BadlistPassword, Value::new_iutf8("1love4life")),
+        (Attribute::BadlistPassword, Value::new_iutf8("212224236248")),
+        (Attribute::BadlistPassword, Value::new_iutf8("2813308004")),
```
Comment (CEbbinghaus) [inline server/lib/src/migration_data/dl8/system_config.rs:65]: Can we codegen these from a common file? during build read all lines from the file and turn each into 1 attribute?

File: server/lib/src/server/migrations.rs [hunk 4]
```diff
@@ -182,9 +176,6 @@ impl QueryServer {
         // we would have skipped the patch level fix which needs to have occurred *first*.
         if reload_required {
             write_txn.reload()?;
-            // We are not yet at the schema phase where reindexes will auto-trigger
-            // so if one was required, do it now.
-            write_txn.reindex(false)?;
```
Comment (CEbbinghaus) [inline server/lib/src/server/migrations.rs:187]: we no long er need to reindex?

File: server/lib/src/server/migrations.rs [hunk 5]
```diff
@@ -294,6 +302,75 @@ impl QueryServerWriteTransaction<'_> {
         }
     }
 
+    /// Migration domain level 7 to 8 (1.4.0)
+    #[instrument(level = "info", skip_all)]
+    pub(crate) fn migrate_domain_7_to_8(&mut self) -> Result<(), OperationError> {
```
Comment (CEbbinghaus) [inline server/lib/src/server/migrations.rs:307]: Not really for this one but I wonder if we can't codegen these methods via a macro rule. would take a little bit of the repetition out especially given that all the methods within the module have the same name

File: server/testkit/defunct_examples/enumerating_access.rs [hunk 6]
```diff
@@ -4,7 +4,9 @@
 //!
 
 use kanidmd_lib::constants::entries::Attribute;
-use kanidmd_lib::constants::groups::{idm_builtin_admin_groups, idm_builtin_non_admin_groups};
+use kanidmd_lib::migration_data::current::{
```
Comment (CEbbinghaus) [inline server/testkit/defunct_examples/enumerating_access.rs:7]: I feel like I'm crazy, but I can't find where the 'current' module is
image

File: server/testkit/src/lib.rs [hunk 7]
```diff
@@ -385,7 +385,7 @@ pub async fn login_put_admin_idm_admins(rsclient: &KanidmClient) {
 
     #[allow(clippy::expect_used)]
     rsclient
-        .idm_group_add_members(BUILTIN_GROUP_IDM_ADMINS_V1.name, &[ADMIN_TEST_USER])
+        .idm_group_add_members("system_admins", &[ADMIN_TEST_USER])
```
Comment (CEbbinghaus) [inline server/testkit/src/lib.rs:388]: why not use the `NAME_SYSTEM_ADMINS` constant?

**Review by CEbbinghaus — APPROVED** [review]
Oh boy that +-. I like where we are heading but I think I'd like to codegen a little more to get rid of some of the boilerplate.

Nothing stopping the PR except some parts I'm unsure about and some magic strings that I would prefer to just pull in from constants.

Note that I did not verify the correctness of the schema and am instead relying on you having copy/pasted all the correct properties for each DL. This was mostly verifying the soundness of the logic surrounding that change.

File: server/lib/src/migration_data/dl8/schema.rs (hunk 2 above)
Comment (Firstyear) [reply server/lib/src/migration_data/dl8/schema.rs:21]: yes, but I just didn't prune all these. They'll age out naturally in time :)

File: server/lib/src/migration_data/dl8/system_config.rs (hunk 3 above)
Comment (Firstyear) [reply server/lib/src/migration_data/dl8/system_config.rs:65]: Probably but that should be it's own PR I think. That's it's own block of work.

File: server/lib/src/server/migrations.rs (hunk 4 above)
Comment (Firstyear) [reply server/lib/src/server/migrations.rs:187]: No, we don't :) I carefully checked this flow, and we don't need it.

File: server/lib/src/server/migrations.rs (hunk 5 above)
Comment (Firstyear) [reply server/lib/src/server/migrations.rs:307]: Yes, we could, but then if we change one migration we have to then duplicate the macro again, and it has it's own issues. I think for now we do it the correct way, then we simplify, then optimise. It may be stupid, but it's correct.

File: server/testkit/defunct_examples/enumerating_access.rs (hunk 6 above)
Comment (Firstyear) [reply server/testkit/defunct_examples/enumerating_access.rs:7]: The example is defunct, the current module doesn't exist. But this example was just too broken in the current work..

File: server/lib/src/migration_data/dl8/access.rs (hunk 1 above)
Comment (Firstyear) [reply server/lib/src/migration_data/dl8/access.rs:56]: Because we model this in the ACP code underneath, I don't remember why I added it like this, but there was probably a reason, most likely so we could have a safe fallback in a parse error of some kind such that the acp will never apply.

Comment (Firstyear) [reply server/lib/src/migration_data/dl8/access.rs:56]: I seem to recall some migration related reason for it too ....

Comment (Firstyear) [reply server/lib/src/migration_data/dl8/access.rs:56]: Ahh found it. It's so that if a filter in the access control has no matches then we map it to a none so that it can clearly indicate no one actually gains the access, and we can shortcut out.

Comment (Firstyear) [reply server/lib/src/migration_data/dl8/access.rs:56]: And that then allows optimisation/caching of resolved access profiles which only map to conditions that apply to someone/something.

File: server/lib/src/migration_data/dl8/schema.rs (hunk 2 above)
Comment (CEbbinghaus) [reply server/lib/src/migration_data/dl8/schema.rs:21]: They'll age like milk. Just want to make sure that we don't set a bad precident for the next set of schema stuff :P

Comment (Firstyear) [reply server/lib/src/migration_data/dl8/schema.rs:21]: I already cleaned up dl10 is more the point.

File: server/lib/src/migration_data/dl8/system_config.rs (hunk 3 above)
Comment (CEbbinghaus) [reply server/lib/src/migration_data/dl8/system_config.rs:65]: Yeah easy. Not wanting it in this PR. Just want it done eventually

**Review by CEbbinghaus — APPROVED** [review]
LGTM 👍
