### PR TITLE
Fix passkey auth flow redirects

### LINKED ISSUE #3077: [htmx] Oauth flows don't redirect when needing to auth with passkey
### I did this
sign in via oauth on mealie, using mobile and passkey

### I expected the following
works

### This happened instead
stay stuck on kanidm

### Kanidm version details
1.4.0-dev

### PR DESCRIPTION
**Pull request by ToxicMushroom**
# Change summary

Swaps the js fetching into redirect logic with an html form

Fixes #3077 

Checklist
- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/core/static/pkhtml.js [hunk 1]
```diff
@@ -8,46 +8,32 @@ function asskey_login(target) {
...
-        fetch(myRequest).then((response) => {
-            if (response.redirected) {
-                window.location.replace(response.url);
-                return;
-            } else {
-                console.error("expected a redirect");
-            }
-        })
+        document.getElementById("cred-form").submit();
     })
```
Comment (yaleman) [inline server/core/static/pkhtml.js:23]: Please add a `catch()` in case of errors that ... at least `console.log`'s it? I ... think this'd be enough
```suggestion
    }).catch((error) => console.log(error))
```

**Review by yaleman — CHANGES_REQUESTED** [review]

File: server/core/static/pkhtml.js (hunk 1 above)
Comment (ToxicMushroom) [reply server/core/static/pkhtml.js]: good idea

**Review by Firstyear — APPROVED** [review]
Very clever solution :)

**Review by yaleman — APPROVED** [review]
