### PR TITLE
CreatedAt/ModifiedAt fix

### LINKED ISSUE #2670: last_modified_cid stores the create time
Changes to an entry do not advance `last_modified_cid` attribute.
Traces led to: https://github.com/kanidm/kanidm/blob/master/server/lib/src/entry.rs#L2298

### PR DESCRIPTION
**Pull request by Firstyear**
# Change summary

- Add a new CreatedAtCid attribute which reflects the creation time from the entry replication metadata
- Improve LastModifiedCid to always reflect the maximum / latest change that occured to the entry.

Fixes #2670 

Checklist

- [ x ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/lib/src/entry.rs [hunk 1]
```diff
@@ -810,6 +825,18 @@ impl Entry<EntryIncremental, EntryNew> {
...
+                        // Set the created_at to now, since we are creating a new conflict entry here.
+                        let created_at_cid = cid.clone();
+
+                        // Bypass add_ava here so that we don't update the ecstate with the
+                        // metadata of these attrs.
+                        let cv = vs_cid![last_mod_cid];
+                        let _ = cnf_ent.attrs.insert(Attribute::LastModifiedCid, cv);
+                        let cv = vs_cid![created_at_cid];
+                        let _ = cnf_ent.attrs.insert(Attribute::CreatedAtCid, cv);
+
```
Comment (yaleman) [inline server/lib/src/entry.rs:839]: Don't need to do the alloc's do we?

```suggestion
                        // Bypass add_ava here so that we don't update the ecstate with the
                        // metadata of these attrs.                        
                        // Setup the last changed to now.
                        let cv = vs_cid![cid.clone()];
                        let _ = cnf_ent.attrs.insert(Attribute::LastModifiedCid, cv);
                        // Set the created_at to now, since we are creating a new conflict entry here.
                        let cv = vs_cid![cid.clone();
                        let _ = cnf_ent.attrs.insert(Attribute::CreatedAtCid, cv);

```

File: server/lib/src/entry.rs [hunk 2]
```diff
@@ -982,11 +1023,24 @@ impl Entry<EntryIncremental, EntryNew> {
...
+                // the created/mod cid's.
+                ecstate.retain(|k, _| schema.is_replicated(k));
+
+                let last_mod_cid = ecstate.get_max_cid();
+                let cv = vs_cid![last_mod_cid.clone()];
+                let _ = eattrs.insert(Attribute::LastModifiedCid, cv);
+
+                let create_at_cid = ecstate.at();
+                let cv = vs_cid![create_at_cid.clone()];
+                let _ = eattrs.insert(Attribute::CreatedAtCid, cv);
```
Comment (yaleman) [inline server/lib/src/entry.rs:1042]: ?
```suggestion
                let cv = vs_cid![ecstate.get_max_cid()];
                let _ = eattrs.insert(Attribute::LastModifiedCid, cv);

                let cv = vs_cid![ecstate.at()];
                let _ = eattrs.insert(Attribute::CreatedAtCid, cv);
```

**Review by yaleman — CHANGES_REQUESTED** [review]
Seems like there's some extra cloney allocs and stuff around?

File: server/lib/src/entry.rs (hunk 1 above)
Comment (Firstyear) [reply server/lib/src/entry.rs:839]: Compiler wise they are "equivalent", and I prefer the extra comments :)

**Comment by Firstyear** [comment]
> Seems like there's some extra cloney allocs and stuff around?

Yeah, CID is clone, not copy. But CID is a tiny type, so I'm not too stressed about it.

File: server/lib/src/entry.rs [hunk 3]
```diff
@@ -826,12 +826,12 @@ impl Entry<EntryIncremental, EntryNew> {
...
 
                         // Bypass add_ava here so that we don't update the ecstate with the
-                        // metadata of these attrs.                        
+                        // metadata of these attrs.
                         // Setup the last changed to now.
                         let cv = vs_cid![cid.clone()];
                         let _ = cnf_ent.attrs.insert(Attribute::LastModifiedCid, cv);
                         // Set the created_at to now, since we are creating a new conflict entry here.
-                        let cv = vs_cid![cid.clone();
+                        let cv = vs_cid![cid.clone()];
```
Comment (yaleman) [inline server/lib/src/entry.rs:834]: :kek:

**Review by yaleman — APPROVED** [review]
