### PR TITLE
20250508 config version

### LINKED ISSUE #3602: 1.6.0: Errors when trying to use replication
### I did this

I upgraded my server.toml to include `version = "2"` and tried to run 1.6.0

### I expected the following

kanidm to run and replicate

### This happened instead

```
May 07 14:19:53 duncan docker[9258]: kanidm        | 📜 Using config file: "/data/server.toml"
May 07 14:19:53 duncan docker[9258]: kanidm        | Unable to parse config from '"/data/server.toml"': TomlError { message: "data did not match any variant of untagged enum ServerConfigUntagged", raw: None, keys: [], span: None }
May 07 14:19:53 duncan docker[9258]: kanidm        | ERROR: Configuration Parse Failure: Custom { kind: InvalidData, error: TomlError { message: "data did not match any variant of untagged enum ServerConfigUntagged", raw: None, keys: [], span: None } }
```

### Kanidm version details

- Output of `kanidm(d) version`: 1.6.0
- Are you running it in a container? If so, which image/tag?: kanidm/server:1.6.0
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): 

### Any other comments

I narrowed it down to the replication peer section.  If I take all the data out of that section kanidmd will start.  I did not see any changes in the syntax of this section in the docs.

Config file:
```
root@duncan:/vol/services/kanidm# sed -e '/#/d' -e '/partner_cert/s/MII.*"/REDACTED"/'< data/server.toml

bindaddress = "[::]:443"
ldapbindaddress = "[::]:636"
db_path = "/data/kanidm.db"
db_fs_type = "zfs"
tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"
log_level = "info"
domain = "home.honig.net"
origin = "https://02.idm.home.honig.net:443"


[online_backup]
path = "/backups/"
schedule = "00 22 * * *"


i_acknowledge_that_replication_is_in_development = true

[replication]
origin = "repl://02.idm.home.honig.net:444"
bindaddress = "[::]:444"

[replication."repl://01.idm.home.honig.net:444"]
type = "mutual-pull"
partner_cert = "REDACTED"
automatic_refresh = true
```

### LINKED ISSUE #3606: OIDC userinfo issues in 1.6.0/1 with some integrations
### I did this

I had/have **Forgejo** set up with Kanidm as an OIDC backend.  
This previously worked fine, but since 1.6.0 (and also now in 1.6.1), I am getting errors.

The same also happens for me in **oauth2-proxy** (it 500s because calling userinfo errors with the same error).  

However, Grafana and my own Golang application still function perfectly fine, so I am unsure if there is anything else I can provide, or workarounds to try?

**//EDIT: Important note** Recreating the oauth2 client can fix this temporarily, but upon a restart the failure is right back

### I expected the following

OIDC to work and me to be authenticated

### This happened instead

The application (Forgejo) displays a 500, Kanidm's logs of the exchange
```
763bff30-40cc-462e-b52c-99168f8d4af5 INFO     request [ 758µs | 23.30% / 100.00% ] method: GET | uri: /ui/oauth2?client_id=git&redirect_uri=https%3A%2F%2Fgit.foxden.network%2Fuser%2Foauth2%2FFoxDen%2Fcallback&response_type=code&scope=email+openid+profile+openid&state=[snip]&code_challenge=[snip]&code_challenge_method=S256 | version: HTTP/1.1
763bff30-40cc-462e-b52c-99168f8d4af5 INFO     ┝━ handle_oauth2_authorise [ 581µs | 22.76% / 76.70% ]
763bff30-40cc-462e-b52c-99168f8d4af5 INFO     │  ┕━ validate_client_auth_info_to_ident [ 409µs | 53.93% ]
763bff30-40cc-462e-b52c-99168f8d4af5 INFO     │     ┕━ ｉ [info]: A valid limited session value exists for this token | event_tag_id: 10
763bff30-40cc-462e-b52c-99168f8d4af5 INFO     ┕━ ｉ [info]:  | latency: 767.427µs | status_code: 303 | kopid: "763bff30-40cc-462e-b52c-99168f8d4af5" | msg: "client redirection sent"
87b0246c-83c1-473c-9938-83ef9f1c8b0e INFO     request [ 16.1ms | 0.80% / 100.00% ] method: POST | uri: /oauth2/token | version: HTTP/1.1
87b0246c-83c1-473c-9938-83ef9f1c8b0e INFO     ┕━ handle_oauth2_token_exchange [ 16.0ms | 8.87% / 99.20% ]
87b0246c-83c1-473c-9938-83ef9f1c8b0e INFO        ┕━ qswt_commit [ 14.6ms | 90.33% ]
e5bd8411-a5e2-47ac-91fb-c3a4ce91e627 INFO     request [ 176µs | 50.25% / 100.00% ] method: GET | uri: /oauth2/openid/git/userinfo | version: HTTP/1.1
e5bd8411-a5e2-47ac-91fb-c3a4ce91e627 INFO     ┝━ handle_oauth2_openid_userinfo [ 87.3µs | 49.75% ]
e5bd8411-a5e2-47ac-91fb-c3a4ce91e627 ERROR    │  ┝━ 🚨 [error]: JWS is signed by a key that is not present in this KeyObject
e5bd8411-a5e2-47ac-91fb-c3a4ce91e627 ERROR    │  ┕━ 🚨 [error]: Unable to verify access token | err: KP0022KeyObjectJwsNotAssociated
e5bd8411-a5e2-47ac-91fb-c3a4ce91e627 WARN     ┕━ 🚧 [warn]:  | latency: 178.537µs | status_code: 400 | kopid: "e5bd8411-a5e2-47ac-91fb-c3a4ce91e627" | msg: "client error"
```

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.6.1`
- Are you running it in a container? If so, which image/tag?: `kanidm/server:latest`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### PR DESCRIPTION
**Pull request by Firstyear**
This addresses the issues with OIDC and Configurations.

Fixes #3606 and Fixes #3602

Checklist

- [ ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
For reference there are three commits here and each commit has a message that describes what it fixes :)

File: server/core/src/config.rs [hunk 1]
```diff
@@ -20,24 +20,29 @@ use url::Url;
...
+
+#[derive(Debug, Deserialize)]
+#[serde(tag = "version")]
+pub enum Version {
+    #[serde(rename = "2")]
+    V2,
+}
+
+// Allowed as the large enum is only short lived at startup to the true config
+#[allow(clippy::large_enum_variant)]
```
Comment (vDorst) [inline server/core/src/config.rs:38]: maybe replace with `#[expect(clippy::large_enum_variant, reason = "Allowed as the large enum is only short lived at startup to the true config")]`.
So you get a warning when it is no longer met and that it can be removed.

Comment (Firstyear) [reply server/core/src/config.rs:38]: I doubt we'll ever be able to remove it until box matching is a thing, so I don't see the value here :(

**Review by yaleman — APPROVED** [review]
gotta love weirdness

File: server/core/src/config.rs [hunk 2]
```diff
@@ -310,6 +334,8 @@ impl ServerConfigUntagged {
 #[derive(Debug, Deserialize, Default)]
 #[serde(deny_unknown_fields)]
 pub struct ServerConfigV2 {
+    #[allow(dead_code)]
+    version: String,
```
Comment (ToxicMushroom) [inline server/core/src/config.rs:338]: I think you should add this to the 1.6.2 release notes ?

I hit this because it was a bit unexpected: 
```
kanidm        | Unable to parse config version from '"/data/server.toml"': TomlError { message: "data did not match any variant of untagged enum VersionDetection", raw: None, keys: [], span: None }
kanidm        | ERROR: Configuration Parse Failure: Custom { kind: InvalidData, error: TomlError { message: "data did not match any variant of untagged enum VersionDetection", raw: None, keys: [], span: None } }
```

Comment (Firstyear) [reply server/core/src/config.rs:338]: We have made a better error message here now, so I think we should be okay now.
