### PR TITLE
Resolve incorrect handling of tokens in logout flow

### LINKED ISSUE #2766: Can't sign out properly
### Discussed in https://github.com/kanidm/kanidm/discussions/2760

<div type='discussions-op-text'>

<sup>Originally posted by **MrSpock** May 11, 2024</sup>
Hi,
I'm evaluating kanidm and I stuck with such basic stuff like logout.
When I login to system and click Sign Out I'm getting following log error and web message:
`kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     request [ 4.50ms | 9.87% / 100.00% ] method: GET | uri: /v1/logout | version: HTTP/1.1
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     ┝━ handle_logout [ 4.06ms | 22.44% / 90.13% ]
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     │  ┝━ validate_client_auth_info_to_ident [ 3.05ms | 67.69% ]
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     │  │  ┕━ ｉ [info]: A valid limited session value exists for this token | event_tag_id: 10
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     │  ┝━ ｉ [info]: modify initiator | event_tag_id: 10 | name: User( spock@*, fc4a6f61-a843-4dbf-bf27-cfc91b0ec0f6 ) (d8ebf915-0b57-4439-b3d9-ea757cf7585e, read write)
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     │  ┝━ ｉ [info]: search | event_tag_id: 10 | initiator: User( spock@idm*, fc4a6f61-a843-4dbf-bf27-cfc91b0ec0f6 ) (d8ebf915-0b57-4439-b3d9-ea757cf7585e, read write)
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 INFO     │  ┝━ ｉ [info]: denied ❌ - no entries were released | event_tag_id: 11
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 ERROR    │  ┝━ 🚨 [error]: modify: no candidates match filter, failure Filter(Valid) (not ( (class eq Iutf8("tombstone") or class eq Iutf8("recycled")) ) and (uuid eq Uuid(fc4a6f61-a843-4dbf-bf27-cfc91b0ec0f6) and user_auth_token_session eq Refer(d8ebf915-0b57-4439-b3d9-ea757cf7585e)))
kanidmd  |  | event_tag_id: 4
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 ERROR    │  ┕━ 🚨 [error]: Failed to destroy user auth token NoMatchingEntries | event_tag_id: 1
kanidmd  | 76071ae1-1f1b-40b6-a9f8-d1d2778420b0 WARN     ┕━ 🚧 [warn]:  | latency: 4.545756ms | status_code: 404 | kopid: "76071ae1-1f1b-40b6-a9f8-d1d2778420b0" | msg: "client error"`
kanidm-signout

What Am I doing wrong ? :)</div>

I wonder if in this case since the auth token is within the grace window, and since it's being used to logout, we should just write a session stub with the revoked state which will cause the async write back to be dropped? It would resolve this error.

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #2766 - Fixes invalid handling of tokens in the logout flow. This was an oversight on my part when adding multi-instance handling. 

Checklist

- [ x ] This pr contains no AI generated code
- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ x ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
Will need to be cherry-picked into 1.2, hopefully won't cause too much issue with a 1.2.2 ....

File: tools/cli/src/cli/session.rs [hunk 1]
```diff
@@ -641,19 +645,24 @@ impl LogoutOpt {
...
-                    Ok(verifier) => verifier,
-                    Err(err) => {
-                        error!(?err, "Unable to configure jws verifier");
-                        std::process::exit(1);
-                    }
-                }
-            } else {
-                error!("Unable to access token public key");
+            let Some(key_id) = jwsc.kid() else {
+                error!("Invalid token, missing KeyID");
```
Comment (yaleman) [inline tools/cli/src/cli/session.rs:649]: Since this is still parsing the local token, if it's invalid why not just log a debug message and remove it from the local store? (same with the rest of this)

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Yeah, I ummed and ahhed a lot about this. The problem is that we need the *spn* to actually ID the token out the store. The spn is collected down in to_client(), and by this part of the process we *must* have done a successful to_client() which means:

* The token *already* has to have passed signature checks for to_client to have worked: https://github.com/kanidm/kanidm/blob/master/tools/cli/src/cli/common.rs#L213
* If logout() succeeded that means the token was *also* validated.

So by this point, unless something bonkers happens, then the validation will always pass.

I did consider using ReleaseNoVerify here, but I think the above meant it was "safe" by that point. 

Really, this is a bit of a tough one layering wise, because we have to handle token state in the client *and* in the cli itself due to the token store. Tech Debt, yay. 

Anywy, I think an addition that could be wise here is removing https://github.com/kanidm/kanidm/blob/master/tools/cli/src/opt/kanidm.rs#L785 hidden from the local_only flag, allowing the token to be removed *always* bypassing all these other checks.

Comment (yaleman) [reply tools/cli/src/cli/session.rs:649]: > So by this point, unless something bonkers happens, then the validation will always pass.

so why error out and leave a broken token in the local cache at that point? just break out of the parsing, remove it from the file and carry on

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Because we haven't been able to bubble up the spn that we need to remove the token.

Comment (yaleman) [reply tools/cli/src/cli/session.rs:649]: This seems like a logical loop. 

1. We got the token from the local token store.
2. We tried to parse it
3. That failed 
4. Now we can't remove it because we can't parse it?

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Which is exactly why I un-hide the local only removal flow. That allows breaking out of the loop.

Comment (yaleman) [reply tools/cli/src/cli/session.rs:649]: But it's a broken token, why not just clean the token store and tell the user what happened, instead of `exit(1)`ing with an error message and leaving them with the broken thing still in the cache? 

Fair enough don't try and send it to the server, but it shouldn't be in the token store at the end of the interaction if it's broken - once you've gotten past line 636 (`client.get_token()`) there's *something* found that can be dealt with, so if validation doesn't work then just clean it up.

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: That's a good point. I think we need to do that in the try_to_client() call though because that affects every possible workflow / interaction.

Comment (yaleman) [reply tools/cli/src/cli/session.rs:649]: That'd work, too 😄

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Reading through this, the logic to add that here is going to be a nightmare actually. I think having unhidden the ability to force remove the token locally is going to have to suffice for now. Also note that kanidm session cleanup catches them too.

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Actually there is a way, spoke too soon.

Comment (Firstyear) [reply tools/cli/src/cli/session.rs:649]: Actually, there isn't.

**Review by yaleman — APPROVED** [review]
