### PR TITLE
Mail substr index

### LINKED ISSUE #2978: LDAP query wildcard matching doesn't work with prefix/suffix
### I did this
`ldapsearch -x -b "dc=id,dc=example,dc=com" "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(mail=*@example.com))"`

### I expected the following
it shows properly matched results that are present when using
`ldapsearch -x -b "dc=id,dc=example,dc=com" "(|(objectClass=posixAccount)(objectClass=posixGroup))"`

### This happened instead
0 matched results

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.4.0-dev (up to date)
- Are you running it in a container? If so, which image/tag?: docker, kanidm/server:devel

### Any other comments
`*` works, while `prefix*` `*suffix` `prefix*suffix` don't work

### PR DESCRIPTION
**Pull request by Firstyear**
Fixes #2978 - needs backport to 1.3 IMO. 

We incorrectly were not applying re-indexing during migrations, and we were not properly handling the new substr entry-no-match-index process on email. 

Checklist

- [ x ] This PR contains no AI generated code
- [ x ] `cargo fmt` has been run
- [ ] `cargo clippy` has been run
- [ x ] `cargo test` has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/lib/src/server/migrations.rs [hunk 1]
```diff
@@ -139,6 +139,9 @@ impl QueryServer {
             // Reload if anything in migrations requires it - this triggers the domain migrations
             // which in turn can trigger schema reloads etc.
             write_txn.reload()?;
+            // Force a reindex here since schema probably changed and we aren't at the
+            // runtime phase where it will trigger on it's own yet.
```
Comment (yaleman) [inline server/lib/src/server/migrations.rs:143]:
```suggestion
            // runtime phase where it will trigger on its own yet.
```

File: server/lib/src/server/migrations.rs [hunk 2]
```diff
@@ -152,6 +155,9 @@ impl QueryServer {
             // We did not already need a version migration as above
             write_txn.domain_remigrate(DOMAIN_PREVIOUS_TGT_LEVEL)?;
             write_txn.reload()?;
+            // Force a reindex here since schema probably changed and we aren't at the
+            // runtime phase where it will trigger on it's own yet.
```
Comment (yaleman) [inline server/lib/src/server/migrations.rs:159]:
```suggestion
            // runtime phase where it will trigger on its own yet.
```

**Review by yaleman — APPROVED** [review]

**Review by yaleman — APPROVED** [review]
