### PR TITLE
20250205 3369 firefox pin

### LINKED ISSUE #3369: Better handling of passkeys without a PIN
### I did this
Tried to enroll my freshly opened Yubikey as a passkey. The Yubikey didn't had a PIN set already.

Nonetheless I could click the "Add Passkey" button, got prompted from my Browser (Firefox 134) to touch it, get onto the second view to name my passkey and then after clicking Save, kanidm ran into an exception.

### I expected the following
Get a helpful error message that tells me that I need to set a pin first, before I could use it as a passkey.

### This happened instead
Kanidm ran into an Exception with the following log:

```
42ff4ef3-8701-49c1-a46d-75f44ff99594 INFO     request [ 2.47ms | 94.95% / 100.00% ] method: POST | uri: /ui/api/finish_passkey | version: HTTP/1.1
42ff4ef3-8701-49c1-a46d-75f44ff99594 INFO     ┝━ handle_idmcredentialupdate [ 125µs | 5.05% ]
42ff4ef3-8701-49c1-a46d-75f44ff99594 ERROR    │  ┕━ 🚨 [error]: Failed to begin credential_passkey_finish | err: InvalidRequestState
42ff4ef3-8701-49c1-a46d-75f44ff99594 ERROR    ┝━ 🚨 [error]:  | latency: 1.915222ms | status_code: 500 | kopid: "42ff4ef3-8701-49c1-a46d-75f44ff99594" | msg: "error handling request"
42ff4ef3-8701-49c1-a46d-75f44ff99594 ERROR    ┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 1 ms
```

### Kanidm version details

- Output of `kanidm(d) version`: kanidm 1.4.5 
- Are you running it in a container? No
- If not a container, how'd you install it: NixOS module
- Operating System / Version: NixOS 24.11 (`Linux sso2 6.6.64 #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec  9 09:33:11 UTC 2024 x86_64 GNU/Linux`)

### Any other comments
Not sure if this can even be done in kanidm, or if I need to raise this issue in Firefox.

### PR DESCRIPTION
**Pull request by Firstyear**
Improve error message when passkey is missing PIN

    Firefox still doesn't support setting a PIN on new devices. Because
    of this we need a way to return a better error message for devices
    that don't have UV configured.

Fixes #3369

Checklist

- [ ] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: tools/cli/src/cli/person.rs [hunk 1]
```diff
@@ -1282,6 +1282,11 @@ fn display_warnings(warnings: &[CURegWarning]) {
             CURegWarning::Unsatisfiable => {
                 println!("Account policy is unsatisfiable. Contact your administrator.");
             }
+            CURegWarning::WebauthnUserVerificationRequired => {
+                println!(
+                    "The passkey you attempted to register did not provide user verification."
```
Comment (yaleman) [inline tools/cli/src/cli/person.rs:1287]:
```suggestion
                    "The passkey you attempted to register did not provide user verification, please ensure a PIN or equivalent is set."
```

**Review by yaleman — APPROVED** [review]
