### PR TITLE
Ensure that privileged sessions expirations are synced

### LINKED ISSUE #3956: Infinite loop occurs with privilege escalation via Reauth
### I did this

I tried reauth as an account in the idm_admin group to change the posix gidnumber, as prompted.

### This happened instead

```
❯ kanidm person posix set-password mnakano
2025-11-14T08:50:24.047247Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:25.192088Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:25.742032Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:25.918380Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:26.075874Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:26.225847Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:26.376199Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:26.518147Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
Would you like to re-authenticate? yes
2025-11-14T08:50:26.660320Z ERROR kanidm_cli::common: Privileges have expired for mnakano@idm.hpcs.cs.tsukuba.ac.jp - you need to re-authenticate again.
```

### Kanidm version details

- Output of `kanidm(d) version`: `kanidm 1.8.0`
- Are you running it in a container? If so, which image/tag?: `kanidm/server:1.8.0`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): `Linux takotanuki 6.12.57-1-lts #1 SMP PREEMPT_DYNAMIC Sun, 02 Nov 2025 15:08:33 +0000 x86_64 GNU/Linux`

### Any other comments

The loop originates in the `to_client` function within `reauth`. Since you lack write permissions, it should have returned `Error::NeedReauth`. However, it attempts to request `Write` permissions in `to_client` without modifying the token, which triggers token validation and leads to a recursive call that causes the loop.

https://github.com/kanidm/kanidm/blob/f2032d61f59e55d61752ed36eb6a9890577a8934/tools/cli/src/cli/common.rs#L338

When testing by hardcoding the `OpType` passed to `to_client` in `reauth` to `OpType::Read`, the expected behavior was achieved.
Since the `reauth` subcommand accepts a `mode` parameter, there's a possibility that specifying `optype` might be required under certain conditions, so I reported this as an Issue rather than a PR.

### PR DESCRIPTION
**Pull request by Firstyear**
Ensure that privileged sessions expirations are synced

    Previously we allowed the privilege time to last longer than the
    session time of the token, since the token expiration *should* take place
    first. However this didn't account for the case when a session may have
    an expiry *shorter* than the limited duration time, which would lead
    priv sessions to be "expired" and then attempt a re-auth which was
    impossible.

    This forces the expirations to be synced at session creation, using
    the shorter of the two expirations between policy and the server
    encoded priv session cap.

Fixes #3956

Checklist

- [x] This PR contains no AI generated code
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: server/lib/src/idm/account.rs [hunk 1]
```diff
@@ -363,14 +358,26 @@ impl Account {
             SessionScope::ReadOnly => (UatPurpose::ReadOnly, expiry),
             SessionScope::ReadWrite => {
                 // These sessions are always rw, and so have limited life.
-                (UatPurpose::ReadWrite { expiry }, limited_expiry)
+                // Ensure that we take the lower of the two bounds.
+                let capped = if expiry < limited_expiry {
+                    expiry
+                } else {
+                    limited_expiry
+                };
```
Comment (yaleman) [inline server/lib/src/idm/account.rs]: Smoother with a min comparison 😄 

```suggestion
                let capped = std::cmp::min(expiry, limited_expiry);
```

**Review by yaleman — DISMISSED** [review]

**Comment by Firstyear** [comment]
I knew there was an easier way! I forgot it's in cmp min damn it.
