### PR TITLE
511 upgrade failure - add debuging tools and improve debugging of the issue.

### LINKED ISSUE #511: Upgrade failure: during restores duplicate entries may be created
During an upgrade, a condition was hit where it became possible to have restores break duplicating entries and potentially mis-indexing content. This is a major issue as restores should always work, and upgrades should not break. 

The situation was that due to running a git master version, an entry had an incorrect syntax for an attribute. After backing up the server, and then restoring with this entry removed from the backup, the server became inconsistent and would not start correctly. 

Starting from a fresh db and restoring did NOT work.

### PR DESCRIPTION
**Pull request by Firstyear**
⚠️  ALL CURRENT VERSIONS OF KANIDM ARE UNABLE TO RESTORE FROM BACKUPS BEFORE THIS PR IS COMMITTED.  ⚠️

YOU MUST TAKE BACKUPS BY STOPPING YOUR SERVER, COPYING THE DATABASE FILES. BACKUPS TAKEN WITH THE BACKUP COMMAND CAN NOT BE RESTORED.

Fixes #511 - During an upgrade I was running a pre-release version of kanidm, where entries had been created that were now "inconsistent" to syntax and schema. I perfomed a backup, and removed the entries that were affected. When restoring, I noticed an issue where the server indicated that ALLIDS was inconsistent. An initial investigation led me to believe that the issue was in concread, where I released 0.2.15 which changed the semantics of is_dirty(). However, this actually made the problem worse - the server was put into a state where the in memory ALLIDS was empty post restore, and so during the reindex phase which is initially un-indexd, a number of system entries were added twice. From this point, the other detections of duplicate entries and various inconsistencies went off preventing further issues. The server was unable to restart. Concread 0.2.16 has been released to undo the changes as they were incorrect.

The failures that contributed:

* Lack of information around the difference in allids leading to confusion that it was the backup file that had the issue, not the server itself.
* Incorrect handling of allids during a restore, where verification was *correctly* flagging an issue with the system state.
* lack of debugging tools to investigate and display the state of id2entry/idx_ tables, which limited the ability to diagnose the problem initially.
* Lack of backend verification in backend restore / backup tests.
* A lack of a test that alters the backup content before the restore is performed. 

This fixes multiple aspects:

* CRITICAL: This corrects the behaviour of allids handling in arc_sqlite so that restores can complete. 
* The addition of db_scan tools as an option to kanidmd which can allow inspection of low-level database content for issue resolution.
* Fixes to the tests to detect this issue.
* extension of allids consistency debugging to display the invalid content / differences. 

- [ x ] cargo fmt has been run
- [ ] cargo clippy has been run
- [ ] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
I've upgraded my personal instance to this branch, and can confirm that backup and restore now work.

File: kanidmd/src/lib/be/idl_arc_sqlite.rs [hunk 1]
```diff
@@ -646,7 +730,13 @@ impl<'a> IdlArcSqliteWriteTransaction<'a> {
...
         self.entry_cache.clear();
         // Write the raw ents
-        self.db.write_identries_raw(au, entries)
+        self.db
+            .write_identries_raw(audit, entries)
+            .and_then(|()| self.db.get_allids(audit))
+            .map(|mut ids| {
+                // Update allids since we cleared them and need to reset it in the cache.
+                std::mem::swap(self.allids.deref_mut(), &mut ids);
+            })
```
Comment (Firstyear) [inline kanidmd/src/lib/be/idl_arc_sqlite.rs:739]: For anyone playing at home - this is the section that fixes the restore process. Everything else is about adding diagnostic tooling, or better logging.
