### PR TITLE
444 - client's config URI missing and more file open handling

### LINKED ISSUE #444: Should show more precise error message when running ``kanidm-unixd``
The following just output `uri (-H) missing, can not proceed`, while it should suggest user to check if `/etc/kanidm/config` file is missing.
```
:~> sudo systemctl status kanidm-unixd
[sudo] password for root: 
● kanidm-unixd.service - Kanidm Local Client Resolver
     Loaded: loaded (/usr/lib/systemd/system/kanidm-unixd.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-05-19 04:52:39 CEST; 6h ago
    Process: 3441 ExecStart=/usr/sbin/kanidm_unixd (code=exited, status=101)
   Main PID: 3441 (code=exited, status=101)
        CPU: 31ms

May 19 04:52:39 localhost.localdomain systemd[1]: Started Kanidm Local Client Resolver.
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: uri (-H) missing, can not proceed
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: thread 'main' panicked at 'not implemented', kanidm_client/src/lib.rs:254:17
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 19 04:52:39 localhost.localdomain systemd[1]: kanidm-unixd.service: Main process exited, code=exited, status=101/n/a
May 19 04:52:39 localhost.localdomain systemd[1]: kanidm-unixd.service: Failed with result 'exit-code'.
```

### PR DESCRIPTION
**Pull request by yaleman**
Starts on #444, adds some more messages

- [x] cargo fmt has been run
- [x] cargo clippy has been run and it is very upset
- [x] cargo test has been run and passes
- [ ] book chapter included (if relevant)
- [ ] design document included (if relevant)

### CODE REVIEW

File: kanidm_client/src/lib.rs [hunk 1]
```diff
@@ -292,7 +295,7 @@ impl KanidmClientBuilder {
         let address = match &self.address {
             Some(a) => a.clone(),
             None => {
-                eprintln!("uri (-H) missing, can not proceed");
+                eprintln!("Configuration option 'uri' missing, cannot continue client startup.");
```
Comment (Firstyear) [inline kanidm_client/src/lib.rs:298]: Should this be error!?

**Review by Firstyear — CHANGES_REQUESTED** [review]

File: kanidm_client/src/lib.rs (hunk 1 above)
Comment (yaleman) [reply kanidm_client/src/lib.rs:298]: Probably if we had a single way of logging ;)

Comment (Firstyear) [reply kanidm_client/src/lib.rs:298]: Ahhh yeah, that. Okay, well in that case all good.
